discord-email: ''
discord-password: ''
lang: en
filter-factionchat: true
filter-essmute: true

channels:
  channel-id:
    tag: Tag # Tag to show on Minecraft chat
    discord-listen: true # Listen Discord -> Minecraft
    minecraft-listen: true # Listen Minecraft -> Discord